markdown: rdiscount
pygments:       true
permalink:      /blog/:title/
paginate:       5

exclude:
    - README.textile
    - Rakefile
    - .htaccess

title:          Sergi Mansilla
url:            http://www.sergimansilla.com
url_blog:       http://www.sergimansilla.com/blog
feed:           atom.xml
baseline:       "See how high your monkey jumps."
description:    "Sergi Mansilla. Experiments about programming, functional programming and monkey brains programming."
keywords:       "programming,development,functional,algorithms,cryptography,f#,javascript,gwt,java"

css:
    - /css/screen.css
    - /css/syntax.css

author:
    name: Sergi Mansilla
    email: sergimansilla@gmail.com
    twitter: http://twitter.com/sergimansilla
    github: http://github.com/sergi
    linkedin: http://nl.linkedin.com/in/smansilla
