markdown: rdiscount
pygments: false
permalink: /blog/:title/
paginate: 5

exclude:
    - README.textile
    - Rakefile
    - .htaccess

title:          Sergi Mansilla
url:            http://sergimansilla.com
url_blog:       http://sergimansilla.com/blog
feed:           /blog/atom.xml
baseline:       "See how high your monkey jumps."
description:    "Sergi Mansilla. Experiments about functional programming and monkey brains programming."
keywords:       "programming,development,functional,algorithms,cryptography,f#,javascript,javascript"

css:
    - /css/screen.css
    - /css/syntax.css

author:
    name: Sergi Mansilla
    email: sergi.mansilla+blog@gmail.com
    twitter: http://twitter.com/sergimansilla
    github: http://github.com/sergi
    gplus: https://plus.google.com/108447529408245632723
    linkedin: http://nl.linkedin.com/in/smansilla
