markdown: rdiscount
pygments:       true
permalink:      /:title/
paginate:       5

exclude:
    - README.textile

title:          Sergi Mansilla
url:            http://www.sergimansilla.com/blog
feed:           /blog/atom.xml
description:    "See how high your monkey jumps."

css:
    - css/screen.css
    - css/syntax.css

author:
    name: Sergi Mansilla
    email: sergimansilla@gmail.com
    twitter: http://twitter.com/sergimansilla
    github: http://github.com/sergi
    linkedin: http://nl.linkedin.com/in/smansilla
